### ISSUE TITLE
This is awesome :)

### ISSUE THREAD

**Issue by loftwah** [nikkigraceofficial/boundaries-mixtape#1]
Never thought I'd see something like this come up on GitHub (Creative Commons license doesn't tend to come up). I'm a hip hop producer and wannabe rapper/dj from Australia.

**Comment by nikkigraceofficial** [comment]
Hehe, wow, you beat me to even telling anyone about it - it's kind of a special thing I'm doing for Pride. :)

**Comment by nikkigraceofficial** [comment]
I'm thinking of including all of the drum samples, too, and obviously a video tutorial/explanation series is in the works.

**Comment by unr** [comment]
Fantastic, this is a great idea. I may have no use for it, but I love how you're sharing this.

**Comment by ghost** [comment]
Love this idea

**Comment by loftwah** [comment]
How did you go?
